
USE SUCOS_VENDAS

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS.BAK'

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS.BAK' WITH INIT

BACKUP DATABASE SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS2.BAK' WITH COMPRESSION
 
EXEC [dbo].[CriaNotaFiscal] '20180401'

BACKUP LOG SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS_LOG.BAK'

BACKUP LOG SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS2_LOG.BAK' WITH COMPRESSION

EXEC [dbo].[CriaNotaFiscal] '20180402'

BACKUP LOG SUCOS_VENDAS TO DISK = 'c:\temp\sql\SUCOS_VENDAS_P2_LOG.BAK'





