
DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)

SET @MATRICULA = '00240'
SET @NOME = 'Cláudia Rodrigues'
SET @PERCENTUAL = 0.10
SET @DATA = '20120312'
SET @FERIAS = 1
SET @BAIRRO = 'Jardins'

INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO]
, [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

SELECT * FROM [TABELA DE VENDEDORES]



DECLARE @CLIENTE VARCHAR(10), @IDADE INT, @DATANASCIMENTO DATE, @CUSTO FLOAT

SET @CLIENTE = 'João'
SET @IDADE = 10
SET @DATANASCIMENTO = '20170110'
SET @CUSTO = 10.23

PRINT @CLIENTE
PRINT @IDADE
PRINT @DATANASCIMENTO
PRINT @CUSTO



DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101'
PRINT @NUMNOTAS

SELECT * FROM [NOTAS FISCAIS] WHERE [DATA] = '20170101'