DECLARE @IDADE INT
DECLARE @NOME VARCHAR(100)
DECLARE @DATA DATE

DECLARE @IDADE2 INT, @NOME2 VARCHAR(100), @DATA2 DATE

SET @IDADE = 20
--PRINT @IDADE

SET @NOME = 'João'
--PRINT @NOME

SET @DATA = '20220510'
--PRINT @DATA


DECLARE @CPF VARCHAR (12)
SET @CPF = '1471156710'

--SELECT NOME, [DATA DE NASCIMENTO], IDADE FROM [TABELA DE CLIENTES]
--WHERE CPF = @CPF

SELECT @NOME2 = NOME, @DATA2 = [DATA DE NASCIMENTO], @IDADE2 = IDADE
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF

PRINT @NOME
PRINT @DATA
PRINT @IDADE