
IF OBJECT_ID ('TABELA DE NUMEROS','U') IS NOT NULL
   DROP TABLE [TABELA DE NUMEROS]

CREATE TABLE [TABELA DE NUMEROS] ([NUMERO] INT, [STATUS] VARCHAR(200))

DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT, @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
   SELECT @CONTADOR_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE [NUMERO] = @LIMITE_MINIMO
   IF @CONTADOR_NOTAS > 0 
       INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É nota fiscal')
   ELSE
       INSERT INTO [TABELA DE NUMEROS] ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'Não é nota fiscal')
   SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1   
END

SELECT * FROM [TABELA DE NUMEROS]

SELECT MIN(NUMERO), MAX(NUMERO)
	FROM [SUCOS_VENDAS].[dbo].[NOTAS FISCAIS]





IF OBJECT_ID('TABELANOTAS','U') IS NOT NULL
DROP TABLE TABELANOTAS
CREATE TABLE TABELANOTAS (DATA DATE, NUMNOTAS INT)
DECLARE @DATAINICIAL DATE
DECLARE @DATAFINAL DATE
DECLARE @NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'
WHILE @DATAINICIAL <= @DATAFINAL
BEGIN
    SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATAINICIAL
    INSERT INTO TABELANOTAS (DATA, NUMNOTAS) 
        VALUES (@DATAINICIAL, @NUMNOTAS)
    SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
END
SELECT * FROM TABELANOTAS