SET SHOWPLAN_ALL OFF

SELECT CPF FROM [TABELA DE CLIENTES] WHERE CIDADE = 'Rio de Janeiro'

SELECT CPF FROM [TABELA DE CLIENTES] WHERE CPF = '1471156710'

 SELECT N FROM Nums1 where N = '10001'

 SELECT N FROM Nums2 where N = '10001'