

SELECT * FROM MASTER.SYS.sql_logins

SELECT name, LOGINPROPERTY(name, 'PasswordLastSetTime') from MASTER.SYS.sql_logins

CREATE LOGIN paulo WITH PASSWORD = 'paulo'

SELECT SERVERPROPERTY('PC-NEW') AS SERVER_NAME
, NAME AS LOGIN_NAME FROM  MASTER.SYS.sql_logins
WHERE PWDCOMPARE(NAME, PASSWORD_HASH) <> 1

