CREATE TABLE TAB_CHECK
(ID INT NOT NULL,
NOME VARCHAR(20) NULL,
IDADE INT NULL,
CIDADE VARCHAR(20) NULL,
CONSTRAINT CHK_PESSOA CHECK (IDADE >= 18))

INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE) VALUES (1, 'JOÃO', 19, 'RIO DE JANEIRO')
INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE) VALUES (2, 'PEDRO', 20, 'SÃO PAULO')

CREATE TABLE TAB_CHECK2
(ID INT NOT NULL,
NOME VARCHAR(20) NULL,
IDADE INT NULL,
CIDADE VARCHAR(20) NULL,
CONSTRAINT CHK_PESSOA2 CHECK (IDADE >= 18 AND CIDADE = 'SÃO PAULO'))


INSERT INTO TAB_CHECK2 (ID, NOME, IDADE, CIDADE) VALUES (2, 'PEDRO', 18, 'RJ')

INSERT INTO TAB_CHECK2 (ID, NOME, IDADE, CIDADE) VALUES (1, 'PEDRO', 18, 'SÃO PAULO')

SELECT * FROM TAB_CHECK2
