CREATE DATABASE [SUCOS_VENDAS_06]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUCOS_VENDAS_06', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS_06.mdf' , 
SIZE = 10240KB , 
MAXSIZE = 25600KB , 
FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'SUCOS_VENDAS_06_log', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS_06_log.ldf' , 
SIZE = 10240KB , 
MAXSIZE = 25600KB , 
FILEGROWTH = 5120KB )
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET ARITHABORT OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET  READ_WRITE 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET RECOVERY FULL 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET  MULTI_USER 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SUCOS_VENDAS_06] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SUCOS_VENDAS_06]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SUCOS_VENDAS_06]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SUCOS_VENDAS_06] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
