INSERT INTO [PRODUTOS] ([CÓDIGO],[DESCRITOR],[SABOR],[TAMANHO],[EMBALAGEM],[PREÇO LISTA])
VALUES ('1040107','Light - 350 ml - Melância', 'Melância', '350 ml', 'Lata', 4.56)

INSERT INTO [PRODUTOS] ([CÓDIGO],[DESCRITOR],[SABOR],[TAMANHO],[EMBALAGEM],[PREÇO LISTA])
VALUES ('1040108','Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00)

INSERT INTO [PRODUTOS] ([CÓDIGO],[DESCRITOR],[SABOR],[TAMANHO],[EMBALAGEM],[PREÇO LISTA])
VALUES 
('1040110','Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 6.00),
('1040111','Light - 350 ml - Manga', 'Manga', '350 ml', 'Lata', 3.50)

select * from PRODUTOS

select * from CLIENTES

INSERT INTO [dbo].[CLIENTES] ([CPF], [NOME], [ENDEREÇO], 
    [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA DE NASCIMENTO], 
    [IDADE], [SEXO], [LIMITE DE CRÉDITO], [VOLUME DA COMPRA], 
    [PRIMEIRA COMPRA])
VALUES ('1471156710', 'Érica Carvalho', 'R. Iriquitia', 'Jardins', 'São Paulo', 
        'SP', '80012212', '19900901', 27, 'F', 170000, 24500,0), 
    ('19290992743', 'Fernando Cavalcante', 'R. Dois de Fevereiro', 'Água Santa', 
        'Rio de Janeiro', 'RJ', '22000000', '20000212', 18, 'M', 100000, 20000, 1), 
    ('2600586709', 'César Teixeira', 'Rua Conde de Bonfim', 'Tijuca', 
        'Rio de Janeiro', 'RJ', '22020001', '20000312', 18, 'M', 120000, 22000, 0)

SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]

INSERT INTO [PRODUTOS] ([CÓDIGO], [DESCRITOR], [SABOR], [TAMANHO], [EMBALAGEM], [PREÇO LISTA])
SELECT [CODIGO DO PRODUTO] AS [CÓDIGO], [NOME DO PRODUTO] AS [DESCRITOR], [SABOR],
[TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] <> '1040107'


INSERT INTO CLIENTES ([CPF],[NOME],[ENDEREÇO],[BAIRRO],
    [CIDADE],[ESTADO],[CEP],[DATA DE NASCIMENTO],[IDADE],
    [SEXO],[LIMITE DE CRÉDITO],[VOLUME DA COMPRA],[PRIMEIRA COMPRA])
SELECT [CPF],[NOME],[ENDERECO 1] AS ENDEREÇO,[BAIRRO],[CIDADE],[ESTADO],
    [CEP],[DATA DE NASCIMENTO],[IDADE],[SEXO],[LIMITE DE CREDITO],
    [VOLUME DE COMPRA],[PRIMEIRA COMPRA]
FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES] 
    WHERE [CPF] NOT IN ('1471156710','19290992743','2600586709')

--INSERÇÃO NAS TABELAS DO BD VENDAS SUCOS