SELECT * FROM PRODUTOS

UPDATE PRODUTOS SET [PREÇO LISTA] = 5, SABOR = 'Laranja'
WHERE CÓDIGO = '1040107'

SELECT * FROM PRODUTOS WHERE SABOR = 'Maracujá'

UPDATE PRODUTOS SET [PREÇO LISTA] = [PREÇO LISTA] * 1.10
WHERE SABOR = 'Maracujá'

SELECT * FROM PRODUTOS WHERE SABOR = 'Maracujá'



SELECT * FROM CLIENTES WHERE CPF = '19290992743'

UPDATE CLIENTES SET 
	ENDEREÇO = 'R. Jorge Emilio 23', 
	BAIRRO = 'Santo Amaro', 
	CIDADE = 'São Paulo', 
	ESTADO = 'SP', 
	CEP = '8833223'
WHERE CPF = '19290992743'

SELECT * FROM CLIENTES WHERE CPF = '19290992743'


SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'

UPDATE CLIENTES SET
	[VOLUME DA COMPRA] = [VOLUME DA COMPRA] * 1.2
WHERE ESTADO = 'RJ'

SELECT * FROM CLIENTES WHERE ESTADO = 'RJ'