--CREATE DATABASE [VENDAS SUCOS]

CREATE TABLE [PRODUTOS]
([CÓDIGO] VARCHAR(10) NOT NULL,
[DESCRITOR] VARCHAR(100) NULL,
[SABOR] VARCHAR(50) NULL,
[TAMANHO] VARCHAR(50) NULL,
[EMBALAGEM] VARCHAR(50) NULL,
[PREÇO LISTA] FLOAT NULL,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CÓDIGO]))

CREATE TABLE [VENDEDORES]
([MATRÍCULA] VARCHAR(5) NOT NULL,
[NOME] VARCHAR(100) NULL,
[BAIRRO] VARCHAR(50) NULL,
[COMISSÃO] FLOAT NULL,
[DATA DE ADMISSÃO] DATE NULL,
[FÉRIAS] BIT NULL,
CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRÍCULA]))

CREATE TABLE [CLIENTES]
([CPF] VARCHAR(11) NOT NULL,
[NOME] VARCHAR(100) NULL,
[ENDEREÇO] VARCHAR(50) NULL,
[BAIRRO] VARCHAR(50) NULL,
[CIDADE] VARCHAR(50) NULL,
[ESTADO] VARCHAR(50) NULL,
[CEP] VARCHAR(8) NULL,
[DATA DE NASCIMENTO] DATE NULL,
[IDADE] INT NULL,
[SEXO] VARCHAR(1) NULL,
[LIMITE DE CRÉDITO] FLOAT NULL,
[VOLUME DA COMPRA] FLOAT NULL,
[PRIMEIRA COMPRA] BIT NULL,
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF]))