INSERT INTO [TABELA PRODUTOS]
([CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1040107',
'Light - 350 ml - Melância',
'Lata',
'350 ml',
'Melância',
4.56)

INSERT INTO [TABELA PRODUTOS]
([CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1037797',
'Clean - 2 Litros - Laranja',
'Pet',
'2 Litros',
'Laranja',
16.01)

INSERT INTO [TABELA PRODUTOS]
([CODIGO DO PRODUTO], 
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES
('1000889',
'Sabor da Montanha - 700 ml - Uva',
'Garrafa',
'700 ml',
'Uva',
6.31)