INSERT INTO [TABELA PRODUTOS]
([CODIGO DO PRODUTO], 
[NOME DO PRODUTO], 
[EMBALAGEM], 
[TAMANHO], 
[SABOR], 
[PRECO DE LISTA])
VALUES
('1002767', 'Videira do Campo', 
'Garrafa', '700 ml','Cereja/Maça', 8.41)

alter table [TABELA PRODUTOS]
ADD CONSTRAINT PK_TABELA_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])

--Para criar PK é necessário que o campo selecionado não aprove Nulos/Null

ALTER TABLE [TABELA PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(20) NOT NULL;


INSERT INTO [TABELA PRODUTOS]
([CODIGO DO PRODUTO], 
[NOME DO PRODUTO], 
[EMBALAGEM], 
[TAMANHO], 
[SABOR], 
[PRECO DE LISTA])
VALUES
(NULL, 'Videira do Campo', 
'Garrafa', '700 ml', NULL, 8.41)

ALTER TABLE [TABELA PRODUTOS]
ADD CONSTRAINT PK_TABELA_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO])