
SELECT X.SABOR, X.ANO, CONVERT(DECIMAL(10,2), X.FATURAMENTO) AS FATURAMENTO, CONVERT(VARCHAR, CONVERT(DECIMAL(10,2),(X.FATURAMENTO/ Y.FATURAMENTO_TOTAL) * 100 ))+ '%' AS PARTICIPACAO
FROM 
(SELECT A.SABOR, YEAR(C.DATA) AS ANO, SUM(B.PREÇO * B.QUANTIDADE) AS FATURAMENTO FROM 
[TABELA DE PRODUTOS] A 
INNER JOIN [ITENS NOTAS FISCAIS] B ON A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
WHERE YEAR(C.DATA) = 2016
GROUP BY A.SABOR, YEAR(C.DATA) 
) X
INNER JOIN
(SELECT YEAR(C.DATA) AS ANO, SUM(B.PREÇO * B.QUANTIDADE) AS FATURAMENTO_TOTAL FROM 
[TABELA DE PRODUTOS] A 
INNER JOIN [ITENS NOTAS FISCAIS] B ON A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] C ON B.NUMERO = C.NUMERO
WHERE YEAR(C.DATA) = 2016
GROUP BY YEAR(C.DATA) 
) Y
ON X.ANO = Y.ANO
ORDER BY X.FATURAMENTO DESC

--Att

SELECT AUX1.TAMANHO, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO, 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO/AUX2.TOTAL) * 100)) + ' %' 
AS PERCENTUAL FROM
(SELECT TP.TAMANHO, YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA)) AUX1
INNER JOIN (SELECT YEAR(NF.DATA) AS ANO, SUM (INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF 
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA)) AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC
